### ISSUE TITLE
Feedback on Project Proposal

### ISSUE THREAD

**Issue by rainerlempert** [UBC-MDS/miniTidyR#1]
Nice work! Thank you for your function descriptions. I think your package construction will allow for, in Tiffany's words, "making good tests, packing it up nicely, collaborating well as a team, making excellent documentation." One small comment:

1. Will your `my_dropna` function remove entire rows that contain `na` values, similar to the Tidyverse's `drop_na`? Or will you replace `na` values with something else? I'll assume the former, just wanted to be sure.
2. Will any of your functions have any other optional arguments?

**Comment by huijuechen** [comment]
1. Will your `my_dropna` function remove entire rows that contain `na` values, similar to the Tidyverse's `drop_na`? Or will you replace `na` values with something else? I'll assume the former, just wanted to be sure.
---- Regarding this, we will remove entire rows that contain `na` values. We will clarify this in the documentation.

**Comment by rainerlempert** [comment]
Sounds good, thank you!
