### ISSUE TITLE
Feedback on Milestone #1

### ISSUE THREAD

**Issue by rainerlempert** [UBC-MDS/miniTidyR#9]
Great job team! Your packages are well organized and your functions are tests are clearly defined. Nice job implementing `roxygen`, way to go above and beyond! A few comments:

- I'm not sure why you have two files for a license.
- It would be good if you could include error messages on your tests. This will make your testing more user friendly. Also defining your tests as "Test 1", "Test 2", ... etc. isn't the most useful practice. It might be better to define your test as something more practical.
- As far as I can tell, all of your tests are on the input to your functions. You should also include tests on the output of your function, for example making sure that the output is in the desired form (data frame) and the output does not equal the input.
- You should try to test some extreme cases, e.g. all values are n/a.

**Comment by ellognea** [comment]
Hi Rainer. Thanks for your feedback.

" I'm not sure why you have two files for a license" : As far as I understand, the license files are automatically created when we ran usethis :: use_mit_license() " . They have different content. The md file contains a description of the license while the other file is liked to the "DESCRIPTION" file . It populates the license line  "License: MIT + file LICENSE"

Jenny's "foofactors tutorial" also has two license files https://github.com/jennybc/foofactors
